version:  '3'


services:
  postgres:
    image: 'postgres:13'
    container_name: 'vsu_mrspo'
    ports:
      - "8080:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: some-db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/